/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Similar;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Similar</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimilarImpl extends ecoConstraintImpl implements Similar
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimilarImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SIMILAR;
  }

} //SimilarImpl
