/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contradict</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContradict()
 * @model
 * @generated
 */
public interface Contradict extends ecoConstraint
{
} // Contradict
