/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deduce</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDeduce()
 * @model
 * @generated
 */
public interface Deduce extends ecoConstraint
{
} // Deduce
