/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>eco Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ecoNode#getNType <em>NType</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ecoNode#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ecoNode#getNDefinition <em>NDefinition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ecoNode#getActivationLevel <em>Activation Level</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ecoNode#getPriority <em>Priority</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ecoNode#getMyAction <em>My Action</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ecoNode#getBDefinition <em>BDefinition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getecoNode()
 * @model
 * @generated
 */
public interface ecoNode extends EObject
{
  /**
   * Returns the value of the '<em><b>NType</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.NodeType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>NType</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>NType</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.NodeType
   * @see #setNType(NodeType)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getecoNode_NType()
   * @model
   * @generated
   */
  NodeType getNType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ecoNode#getNType <em>NType</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>NType</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.NodeType
   * @see #getNType()
   * @generated
   */
  void setNType(NodeType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getecoNode_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ecoNode#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>NDefinition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>NDefinition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>NDefinition</em>' attribute.
   * @see #setNDefinition(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getecoNode_NDefinition()
   * @model
   * @generated
   */
  String getNDefinition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ecoNode#getNDefinition <em>NDefinition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>NDefinition</em>' attribute.
   * @see #getNDefinition()
   * @generated
   */
  void setNDefinition(String value);

  /**
   * Returns the value of the '<em><b>Activation Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Activation Level</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activation Level</em>' attribute.
   * @see #setActivationLevel(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getecoNode_ActivationLevel()
   * @model
   * @generated
   */
  String getActivationLevel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ecoNode#getActivationLevel <em>Activation Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activation Level</em>' attribute.
   * @see #getActivationLevel()
   * @generated
   */
  void setActivationLevel(String value);

  /**
   * Returns the value of the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Priority</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' attribute.
   * @see #setPriority(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getecoNode_Priority()
   * @model
   * @generated
   */
  int getPriority();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ecoNode#getPriority <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' attribute.
   * @see #getPriority()
   * @generated
   */
  void setPriority(int value);

  /**
   * Returns the value of the '<em><b>My Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>My Action</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>My Action</em>' reference.
   * @see #setMyAction(Action)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getecoNode_MyAction()
   * @model
   * @generated
   */
  Action getMyAction();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ecoNode#getMyAction <em>My Action</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>My Action</em>' reference.
   * @see #getMyAction()
   * @generated
   */
  void setMyAction(Action value);

  /**
   * Returns the value of the '<em><b>BDefinition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>BDefinition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>BDefinition</em>' attribute.
   * @see #setBDefinition(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getecoNode_BDefinition()
   * @model
   * @generated
   */
  String getBDefinition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ecoNode#getBDefinition <em>BDefinition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>BDefinition</em>' attribute.
   * @see #getBDefinition()
   * @generated
   */
  void setBDefinition(String value);

} // ecoNode
