/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Explain</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExplain()
 * @model
 * @generated
 */
public interface Explain extends ecoConstraint
{
} // Explain
