/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Incompatible</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIncompatible()
 * @model
 * @generated
 */
public interface Incompatible extends ecoConstraint
{
} // Incompatible
