/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CoEthDSLImpl <em>Co Eth DSL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CoEthDSLImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCoEthDSL()
   * @generated
   */
  int CO_ETH_DSL = 0;

  /**
   * The feature id for the '<em><b>Model Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CO_ETH_DSL__MODEL_NAME = 0;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CO_ETH_DSL__ENTITIES = 1;

  /**
   * The number of structural features of the '<em>Co Eth DSL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CO_ETH_DSL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AgentImpl <em>Agent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AgentImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAgent()
   * @generated
   */
  int AGENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__FEATURES = 1;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__OPERATIONS = 2;

  /**
   * The feature id for the '<em><b>Deco Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__DECO_NODES = 3;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__CONSTRAINTS = 4;

  /**
   * The number of structural features of the '<em>Agent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ecoNodeImpl <em>eco Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ecoNodeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getecoNode()
   * @generated
   */
  int ECO_NODE = 2;

  /**
   * The feature id for the '<em><b>NType</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_NODE__NTYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_NODE__NAME = 1;

  /**
   * The feature id for the '<em><b>NDefinition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_NODE__NDEFINITION = 2;

  /**
   * The feature id for the '<em><b>Activation Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_NODE__ACTIVATION_LEVEL = 3;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_NODE__PRIORITY = 4;

  /**
   * The feature id for the '<em><b>My Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_NODE__MY_ACTION = 5;

  /**
   * The feature id for the '<em><b>BDefinition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_NODE__BDEFINITION = 6;

  /**
   * The number of structural features of the '<em>eco Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_NODE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ActionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>ADefinition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ADEFINITION = 1;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ecoConstraintImpl <em>eco Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ecoConstraintImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getecoConstraint()
   * @generated
   */
  int ECO_CONSTRAINT = 4;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_CONSTRAINT__COOPERATIVE_UNITS = 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_CONSTRAINT__SOURCE = 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_CONSTRAINT__TARGET = 2;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_CONSTRAINT__WEIGHT = 3;

  /**
   * The number of structural features of the '<em>eco Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECO_CONSTRAINT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FacilitateImpl <em>Facilitate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FacilitateImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFacilitate()
   * @generated
   */
  int FACILITATE = 5;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACILITATE__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACILITATE__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACILITATE__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACILITATE__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Facilitate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACILITATE_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TriggerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 6;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InhibitImpl <em>Inhibit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InhibitImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInhibit()
   * @generated
   */
  int INHIBIT = 7;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHIBIT__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHIBIT__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHIBIT__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHIBIT__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Inhibit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHIBIT_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IncompatibleImpl <em>Incompatible</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IncompatibleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIncompatible()
   * @generated
   */
  int INCOMPATIBLE = 8;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCOMPATIBLE__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCOMPATIBLE__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCOMPATIBLE__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCOMPATIBLE__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Incompatible</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCOMPATIBLE_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExplainImpl <em>Explain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExplainImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExplain()
   * @generated
   */
  int EXPLAIN = 9;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLAIN__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLAIN__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLAIN__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLAIN__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Explain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLAIN_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DeduceImpl <em>Deduce</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DeduceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDeduce()
   * @generated
   */
  int DEDUCE = 10;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEDUCE__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEDUCE__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEDUCE__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEDUCE__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Deduce</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEDUCE_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ContradictImpl <em>Contradict</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ContradictImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContradict()
   * @generated
   */
  int CONTRADICT = 11;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRADICT__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRADICT__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRADICT__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRADICT__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Contradict</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRADICT_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SimilarImpl <em>Similar</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SimilarImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSimilar()
   * @generated
   */
  int SIMILAR = 12;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMILAR__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMILAR__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMILAR__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMILAR__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Similar</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMILAR_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CompeteImpl <em>Compete</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CompeteImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCompete()
   * @generated
   */
  int COMPETE = 13;

  /**
   * The feature id for the '<em><b>Cooperative Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPETE__COOPERATIVE_UNITS = ECO_CONSTRAINT__COOPERATIVE_UNITS;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPETE__SOURCE = ECO_CONSTRAINT__SOURCE;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPETE__TARGET = ECO_CONSTRAINT__TARGET;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPETE__WEIGHT = ECO_CONSTRAINT__WEIGHT;

  /**
   * The number of structural features of the '<em>Compete</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPETE_FEATURE_COUNT = ECO_CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FeatureImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.NodeType <em>Node Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.NodeType
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodeType()
   * @generated
   */
  int NODE_TYPE = 15;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CoEthDSL <em>Co Eth DSL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Co Eth DSL</em>'.
   * @see org.xtext.example.mydsl.myDsl.CoEthDSL
   * @generated
   */
  EClass getCoEthDSL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CoEthDSL#getModelName <em>Model Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Model Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.CoEthDSL#getModelName()
   * @see #getCoEthDSL()
   * @generated
   */
  EAttribute getCoEthDSL_ModelName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.CoEthDSL#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.xtext.example.mydsl.myDsl.CoEthDSL#getEntities()
   * @see #getCoEthDSL()
   * @generated
   */
  EReference getCoEthDSL_Entities();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Agent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Agent</em>'.
   * @see org.xtext.example.mydsl.myDsl.Agent
   * @generated
   */
  EClass getAgent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Agent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Agent#getName()
   * @see #getAgent()
   * @generated
   */
  EAttribute getAgent_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Agent#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see org.xtext.example.mydsl.myDsl.Agent#getFeatures()
   * @see #getAgent()
   * @generated
   */
  EReference getAgent_Features();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Agent#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.example.mydsl.myDsl.Agent#getOperations()
   * @see #getAgent()
   * @generated
   */
  EReference getAgent_Operations();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Agent#getDecoNodes <em>Deco Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Deco Nodes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Agent#getDecoNodes()
   * @see #getAgent()
   * @generated
   */
  EReference getAgent_DecoNodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Agent#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see org.xtext.example.mydsl.myDsl.Agent#getConstraints()
   * @see #getAgent()
   * @generated
   */
  EReference getAgent_Constraints();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ecoNode <em>eco Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>eco Node</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoNode
   * @generated
   */
  EClass getecoNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ecoNode#getNType <em>NType</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>NType</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoNode#getNType()
   * @see #getecoNode()
   * @generated
   */
  EAttribute getecoNode_NType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ecoNode#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoNode#getName()
   * @see #getecoNode()
   * @generated
   */
  EAttribute getecoNode_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ecoNode#getNDefinition <em>NDefinition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>NDefinition</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoNode#getNDefinition()
   * @see #getecoNode()
   * @generated
   */
  EAttribute getecoNode_NDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ecoNode#getActivationLevel <em>Activation Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Activation Level</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoNode#getActivationLevel()
   * @see #getecoNode()
   * @generated
   */
  EAttribute getecoNode_ActivationLevel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ecoNode#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoNode#getPriority()
   * @see #getecoNode()
   * @generated
   */
  EAttribute getecoNode_Priority();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.ecoNode#getMyAction <em>My Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>My Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoNode#getMyAction()
   * @see #getecoNode()
   * @generated
   */
  EReference getecoNode_MyAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ecoNode#getBDefinition <em>BDefinition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>BDefinition</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoNode#getBDefinition()
   * @see #getecoNode()
   * @generated
   */
  EAttribute getecoNode_BDefinition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Action#getADefinition <em>ADefinition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ADefinition</em>'.
   * @see org.xtext.example.mydsl.myDsl.Action#getADefinition()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_ADefinition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ecoConstraint <em>eco Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>eco Constraint</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoConstraint
   * @generated
   */
  EClass getecoConstraint();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.ecoConstraint#getCooperativeUnits <em>Cooperative Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Cooperative Units</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoConstraint#getCooperativeUnits()
   * @see #getecoConstraint()
   * @generated
   */
  EReference getecoConstraint_CooperativeUnits();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.ecoConstraint#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoConstraint#getSource()
   * @see #getecoConstraint()
   * @generated
   */
  EReference getecoConstraint_Source();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.ecoConstraint#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoConstraint#getTarget()
   * @see #getecoConstraint()
   * @generated
   */
  EReference getecoConstraint_Target();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ecoConstraint#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight</em>'.
   * @see org.xtext.example.mydsl.myDsl.ecoConstraint#getWeight()
   * @see #getecoConstraint()
   * @generated
   */
  EAttribute getecoConstraint_Weight();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Facilitate <em>Facilitate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Facilitate</em>'.
   * @see org.xtext.example.mydsl.myDsl.Facilitate
   * @generated
   */
  EClass getFacilitate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see org.xtext.example.mydsl.myDsl.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Inhibit <em>Inhibit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inhibit</em>'.
   * @see org.xtext.example.mydsl.myDsl.Inhibit
   * @generated
   */
  EClass getInhibit();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Incompatible <em>Incompatible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Incompatible</em>'.
   * @see org.xtext.example.mydsl.myDsl.Incompatible
   * @generated
   */
  EClass getIncompatible();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Explain <em>Explain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Explain</em>'.
   * @see org.xtext.example.mydsl.myDsl.Explain
   * @generated
   */
  EClass getExplain();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Deduce <em>Deduce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deduce</em>'.
   * @see org.xtext.example.mydsl.myDsl.Deduce
   * @generated
   */
  EClass getDeduce();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Contradict <em>Contradict</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contradict</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contradict
   * @generated
   */
  EClass getContradict();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Similar <em>Similar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Similar</em>'.
   * @see org.xtext.example.mydsl.myDsl.Similar
   * @generated
   */
  EClass getSimilar();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Compete <em>Compete</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compete</em>'.
   * @see org.xtext.example.mydsl.myDsl.Compete
   * @generated
   */
  EClass getCompete();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.xtext.example.mydsl.myDsl.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Feature#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Feature#getType()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Type();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.NodeType <em>Node Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Node Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.NodeType
   * @generated
   */
  EEnum getNodeType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CoEthDSLImpl <em>Co Eth DSL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CoEthDSLImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCoEthDSL()
     * @generated
     */
    EClass CO_ETH_DSL = eINSTANCE.getCoEthDSL();

    /**
     * The meta object literal for the '<em><b>Model Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CO_ETH_DSL__MODEL_NAME = eINSTANCE.getCoEthDSL_ModelName();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CO_ETH_DSL__ENTITIES = eINSTANCE.getCoEthDSL_Entities();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AgentImpl <em>Agent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AgentImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAgent()
     * @generated
     */
    EClass AGENT = eINSTANCE.getAgent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENT__NAME = eINSTANCE.getAgent_Name();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENT__FEATURES = eINSTANCE.getAgent_Features();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENT__OPERATIONS = eINSTANCE.getAgent_Operations();

    /**
     * The meta object literal for the '<em><b>Deco Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENT__DECO_NODES = eINSTANCE.getAgent_DecoNodes();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENT__CONSTRAINTS = eINSTANCE.getAgent_Constraints();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ecoNodeImpl <em>eco Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ecoNodeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getecoNode()
     * @generated
     */
    EClass ECO_NODE = eINSTANCE.getecoNode();

    /**
     * The meta object literal for the '<em><b>NType</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECO_NODE__NTYPE = eINSTANCE.getecoNode_NType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECO_NODE__NAME = eINSTANCE.getecoNode_Name();

    /**
     * The meta object literal for the '<em><b>NDefinition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECO_NODE__NDEFINITION = eINSTANCE.getecoNode_NDefinition();

    /**
     * The meta object literal for the '<em><b>Activation Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECO_NODE__ACTIVATION_LEVEL = eINSTANCE.getecoNode_ActivationLevel();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECO_NODE__PRIORITY = eINSTANCE.getecoNode_Priority();

    /**
     * The meta object literal for the '<em><b>My Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ECO_NODE__MY_ACTION = eINSTANCE.getecoNode_MyAction();

    /**
     * The meta object literal for the '<em><b>BDefinition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECO_NODE__BDEFINITION = eINSTANCE.getecoNode_BDefinition();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ActionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '<em><b>ADefinition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__ADEFINITION = eINSTANCE.getAction_ADefinition();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ecoConstraintImpl <em>eco Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ecoConstraintImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getecoConstraint()
     * @generated
     */
    EClass ECO_CONSTRAINT = eINSTANCE.getecoConstraint();

    /**
     * The meta object literal for the '<em><b>Cooperative Units</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ECO_CONSTRAINT__COOPERATIVE_UNITS = eINSTANCE.getecoConstraint_CooperativeUnits();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ECO_CONSTRAINT__SOURCE = eINSTANCE.getecoConstraint_Source();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ECO_CONSTRAINT__TARGET = eINSTANCE.getecoConstraint_Target();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECO_CONSTRAINT__WEIGHT = eINSTANCE.getecoConstraint_Weight();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FacilitateImpl <em>Facilitate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FacilitateImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFacilitate()
     * @generated
     */
    EClass FACILITATE = eINSTANCE.getFacilitate();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TriggerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InhibitImpl <em>Inhibit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InhibitImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInhibit()
     * @generated
     */
    EClass INHIBIT = eINSTANCE.getInhibit();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IncompatibleImpl <em>Incompatible</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IncompatibleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIncompatible()
     * @generated
     */
    EClass INCOMPATIBLE = eINSTANCE.getIncompatible();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExplainImpl <em>Explain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExplainImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExplain()
     * @generated
     */
    EClass EXPLAIN = eINSTANCE.getExplain();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DeduceImpl <em>Deduce</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DeduceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDeduce()
     * @generated
     */
    EClass DEDUCE = eINSTANCE.getDeduce();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ContradictImpl <em>Contradict</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ContradictImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContradict()
     * @generated
     */
    EClass CONTRADICT = eINSTANCE.getContradict();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SimilarImpl <em>Similar</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SimilarImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSimilar()
     * @generated
     */
    EClass SIMILAR = eINSTANCE.getSimilar();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CompeteImpl <em>Compete</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CompeteImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCompete()
     * @generated
     */
    EClass COMPETE = eINSTANCE.getCompete();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FeatureImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__TYPE = eINSTANCE.getFeature_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.NodeType <em>Node Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.NodeType
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodeType()
     * @generated
     */
    EEnum NODE_TYPE = eINSTANCE.getNodeType();

  }

} //MyDslPackage
