/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTrigger()
 * @model
 * @generated
 */
public interface Trigger extends ecoConstraint
{
} // Trigger
